version: '3.4'
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    command: "npm run start"
    ports:
     - "3000:3000"
    expose:
      - "3000"
    volumes:
      - .:/app
  mongoinstance:
    image: "mongo:latest"
    command: "mongod --port 27017 --dbpath /data/db --replSet rs0 --bind_ip mongoinstance"
    ports:
      - "27017:27017"
    expose:
      - "27017"